### PR TITLE
add new arguments to the LocalstackEndpointResolver.construct_endpoint method

### PR DESCRIPTION
**Pull request by Andrew-Wichmann**
I am not sure if localstack supports these features or not.

### CODE REVIEW

**Comment by jtdoepke** [comment]
Do we need these now? I'd rather finish the https://github.com/mintel/pytest-localstack/tree/v2 rewrite branch than make a new v1 release.

**Comment by Andrew-Wichmann** [comment]
I can get by, but v1 is incompatible with the latest botocore

**Comment by sleightsec** [comment]
been 6 months since work was done on that branch. If this is a dead project, so be it...

**Comment by Andrew-Wichmann** [comment]
@jtdoepke I just hit this again. Any advice on getting around this?

**Comment by jtdoepke** [comment]
@Andrew-Wichmann I'll merge this and make a new release.

**Pull request closed without merging**
